esphome:
  name: petkitp530
  friendly_name: PetkitP530
  platformio_options:
    board_upload.flash_size: 2MB
    board_upload.maximum_size: 2097152
  on_boot:
    then:
      - sensor.template.publish:
          id: silica_days_left_sensor
          state: !lambda 'return id(silica_days_left);'
      - pcf8563.read_time
      - pkt_p530.init:
          on_error:
          - script.execute: init_failed

      - pkt_p530.beep:
          continue_on_error: true
          on_ms: 200
          count: 1

      - pkt_p530.door_open:
          on_error:
          - script.execute: init_failed

      - pkt_p530.door_close:
          on_error:
          - script.execute: init_failed

      - pkt_p530.led_upper:
          on_ms: 65535
          count: 65535

esp8266:
  board: esp01_1m

logger:
  level: DEBUG
  hardware_uart: UART1
  baud_rate: 0 # disable UART logger

wifi:
  id: wifi_
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

uart:
  id: isd91230
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200
  debug:
    sequence:
      lambda: UARTDebug::log_hex(direction, bytes, ' ');

i2c:
  - id: pcf8563_i2c
    scl: GPIO14
    sda: GPIO5

pkt_p530:
  id: feeder
  uart_id: isd91230

globals:
  - id: silica_days_left
    type: int
    restore_value: true
    initial_value: '30'

  - id: silica_last_day
    type: int
    restore_value: true
    initial_value: '0'

sensor:
  - platform: pkt_p530
    id: feeder
    dispensed_portions:
      name: "Feed dispensed portions"

  - platform: template
    id: silica_days_left_sensor
    name: "Silica gel days left"
    unit_of_measurement: "days"
    accuracy_decimals: 0

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO13
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Manual feed"
    filters:
      - delayed_on_off: 500ms
    on_press: 
      then:
        - script.execute:
            id: feed
            portions: 5

  - platform: gpio
    pin: 
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Safe Mode Button"
    on_multi_click:
      - timing:
          - ON for at least 5s
        then:
          - button.press: safe_mode_button

  - platform: pkt_p530
    id: feeder
    door_opened:
      name: "Door opened"
    food_low:
      name: "Low food"
    door_issue:
      name: "Door issue"

  - platform: template
    name: "Silica gel needs replacement"
    device_class: problem
    lambda: |-
      return id(silica_days_left) <= 0;

button:
  - platform: safe_mode
    id: safe_mode_button

  - platform: template
    name: "Feed cat!"
    icon: mdi:food-drumstick
    on_press: 
      then:
        - script.execute:
            id: feed
            portions: 5

  - platform: template
    name: "Replace silica gel"
    icon: mdi:refresh
    on_press:
      then:
        - lambda: |-
            id(silica_days_left) = 30;

        - sensor.template.publish:
            id: silica_days_left_sensor
            state: 30

time:
  - platform: pcf8563
    id: pcf8563_time
    address: 0x51
  - platform: homeassistant
    id: ha_time
    on_time_sync:
      then:
        pcf8563.write_time
    on_time:
      - cron: '00 00 00 * * *'
        then:
          - script.execute: update_silica_gel_sensor
      - cron: '00 00 09 * * *'
        then:
          - script.execute:
              id: feed
              portions: 5
      - cron: '00 00 21 * * *'
        then:
          - script.execute:
              id: feed
              portions: 5

script:
  - id: bootup
    mode: single
    then:
      - sensor.template.publish:
          id: silica_days_left_sensor
          state: !lambda 'return id(silica_days_left);'
      - pcf8563.read_time
      - pkt_p530.init:
          on_error:
          - script.execute: boot_failed
      - pkt_p530.beep:
          preset: "short"
          count: 1
      - pkt_p530.door_open:
          on_error:
          - script.execute: boot_failed
      - delay: 2s
      - pkt_p530.door_close:
          on_error:
          - script.execute: boot_failed
      - pkt_p530.led_upper: "steady_on"

  - id: boot_failed
    mode: restart
    then:
      - logger.log:
          format: "Ooops, init failed!"
          level: "INFO"
      - pkt_p530.beep: "short"
      - pkt_p530.door_close:
      - pkt_p530.led_lower: "blink_fast"
      - script.stop: feed

  - id: feed
    mode: single
    parameters:
      portions: int
    then:
      - logger.log:
          format: "Feeding..."
          level: "INFO"
      - if:
          condition:
            pkt_p530.has_food
          then:
            - pkt_p530.door_open:
                on_error:
                  - logger.log:
                      format: "Can't open door: abort feeding"
                      level: "ERROR"
                  - pkt_p530.door_close:
                  - pkt_p530.beep: "short"
                  - script.stop: feed

            - pkt_p530.dispense:
                portions: !lambda return portions;
                on_error:
                  - logger.log:
                      format: "Dispensing failed"
                      level: "ERROR"
                  - pkt_p530.door_close:
                  - pkt_p530.beep: "short"
                  - script.stop: feed

            - lambda: |-
                id(daily_portions) += portions;
                id(daily_portions_sensor).publish_state(id(daily_portions));

                auto now = id(ha_time).now();
                if (now.is_valid())
                  id(feeding_event).publish_state(now.strftime("%Y-%m-%d %H:%M:%S"));

            - pkt_p530.door_close:
                on_error:
                  - logger.log:
                      format: "Door close door: abort feeding"
                      level: "ERROR"
                  - pkt_p530.beep: "short"
                  - script.stop: feed

            - pkt_p530.led_lower: "steady_off"

            - logger.log:
                format: "Feeding complete, meow"
                level: "INFO"

          else:
            - logger.log:
                format: "NO FOOD!"
                level: "ERROR"
            - pkt_p530.beep: "long"
